# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Workout.create(name: "Russian Twists", type: "Core", description: "Russian twists are a core body exercise that strengthens all parts of your abdominals, including your obliques, for a toned waistline and a stronger back. ", level: "beginner ", directions: "Sit on the floor, with your heels touching the floor or lifted (more advanced) and your hands at your chest. Twist from side to side. ")
Workout.create(name: "Bycicle Crunch", type: "Core", description: "Bicycle crunches are a great way to target the rectus abdominis and the obliques in one easy exercise. . .", level: "intermediate", directions: "Lie flat on the floor with your lower back pressed to the ground (pull your navel in to also target your deep abs). Put your hands behind your head, then bring your knees in towards your chest and lift your shoulder blades off the ground, but be sure not to pull on your neck. Straighten your right leg out to about a 45-degree angle to the ground while turning your upper body to the left, bringing your right elbow towards the left knee. Make sure your rib cage is moving and not just your elbows. Now switch sides and do the same motion on the other side to complete one rep. Do three sets of 20 reps.")
Workout.create(name: "Plank Jacks", type: "Core", description: "The plank jack is a combination of two very common exercises: the plank and (big surprise) the jumping jack", level: "expert", directions: "Start in low plank position with feet hip-width apart. Hop your feet out wider than hip-width, and then hop back to the starting position. Keep your abs tight and don't allow your butt to pop up above the height of your shoulders")
Workout.create(name: "Half-burpee", type: "Cardio", description: "half burpee is a calisthenics and cardiovascular exercise that primarily targets the quads and to a lesser degree also targets the abs, calves, chest, forearms, glutes, hamstrings, hip flexors, lower back, middle back, shoulders and triceps", level: "beginner", directions: "set up in the high plank position with your hands under your shoulders and your feet about shoulder-width apart. Then jump both feet up and outside your hands so your in a squat position. ")
Workout.create(name: "Mountain Climbers", type: "Cardio", description: "Mountain climbers are great for building cardio endurance, core strength, and agility.", level: "intermediate", directions: "Start in high plank position with your shoulders over your wrists. Quickly drive each knee into your chest one at a time as if you're running.")
Workout.create(name: "Squat Jump", type: "Cardio", description: "Engage your whole core and lower body is involved in the simple movement; you'll recruit your abs, glutes, hamstrings, lower back to do it right.", level: "expert", directions: "As you rise, jump up, fully extending legs and pushing arms down to help with momentum. Land lightly on toes and immediately drop into a squat again")
Workout.create(name: "Pullups", type: "Upper body", description: "Pull-ups work every muscle in your upper body. Pull-ups are what we call a "compound exercise," meaning they work out several muscle groups at once. ", level: "beginner", directions: "Pull yourself up by pulling your elbows down to the floor. Keep your elbows close. Pull yourself all the way up until your chin passes the bar. Don't do half reps." 
Workout.create(name: "Chin-ups", type: "Upper body", description: "chinup is a strength training exercise. People frequently do this exercise with the intention of strengthening muscles such as the latissimus dorsi and biceps, which extend the shoulder and flex the elbow, respectively. In this maneuver, the palms are faced towards the body.", level: "intermediate", directions: "Grab the pull-up bar with the palms facing your torso and a grip closer than the shoulder width. As you have both arms extended in front of you holding the bar at the chosen grip width, keep your torso as straight as possible while creating a curvature on your lower back and sticking your chest out. This is your starting position. Tip: Keeping the torso as straight as possible maximizes biceps stimulation while minimizing back involvement. As you breathe out, pull your torso up until your head is around the level of the pull-up bar. Concentrate on using the biceps muscles in order to perform the movement. Keep the elbows close to your body. Tip: The upper torso should remain stationary as it moves through space and only the arms should move. The forearms should do no other work other than hold the bar. After a second of squeezing the biceps in the contracted position, slowly lower your torso back to the starting position; when your arms are fully extended. Breathe in as you")
Workout.create(name: "Push-ups", type: "Upper body", description: "A push-up or press-up if the hands are wider than shoulders placing more emphasis on the pectoral muscles) is a common calisthenics exercise beginning from the prone position. By raising and lowering the body using the arms, push-ups exercise the pectoral muscles, triceps, and anterior deltoids, with ancillary benefits to the rest of the deltoids, serratus anterior, coracobrachialis and the midsection as a whole. Push-ups are a basic exercise used in civilian athletic training or physical education and commonly in military physical training. They are also a common form of punishment used in the military, school sport, or in some martial arts disciplines", level: "expert")
Workout.create(name: "Squat", type: "Lower body", description: "The Squat is a lower body exercise. You can do the bodyweight version, without added resistance", level: "beginner", directions: "Find a foot stance that feels best for you. Pointing your toes slightly outwards helps some, but keeping them parallel is fine, too. If you're not sure what's best, start by putting your feet shoulder-width apart and pointed about 15 degrees outwards.Tense your abs like someone is about to punch you. Look straight ahead and stand tall!")
Workout.create(name: "Lunge", type: "Lower body", description: "Lunges can help you develop lower-body strength and endurance. They're also a great beginner move. When done correctly, lunges can effectively target your lower-body muscles without placing added strain on your joints.", level: "intermediate", directions: "Start with feet shoulder-width apart. Take a step forward, dropping your hips until both knees are are parallel with the hips, quads perpendicular to the shins. Push off with your forward foot and return to the original position, or bring the back leg parallel with the front. Repeat the action with the other leg. Once you've mastered the unweighted version, put a dumbbell in each hand for a challenge that will pay dividends with every step you take")
Workout.create(name: "Deadlifts", type: "Lower body", description: "he deadlift is a weight training exercise in which a loaded barbell or bar is lifted off the ground to the level of the hips, torso perpendicular to the floor, before being placed back on the ground.", level: "expert", directions: " To perform a traditional deadlift, grip the weight on the floor, with feet hip-width apart. Keeping your back absolutely straight, push through the floor with your feet, rising with the weight until you're standing tall with the weight at waist level. (Warning: the deadlift targets vulnerable structures in your back more than any other lower body lift; bad form is not just counterproductive but potentially crippling.)")